version: 1.0.{build}

before_build:
    - cmd: >-        
        git clone https://github.com/Microsoft/rDSN.git main
        
        cd main 
        
        SET DSN_AUTO_TEST=1
        
        run.cmd setup-env
        
        run.cmd build Debug .\build
        
        run.cmd install Debug .\build
        
        cd ..
        
build_script:
    - cmd: >-
        main\run.cmd build Debug .\build
        
        main\run.cmd install Debug .\build
        
        xcopy /Y /S .\build\* .\main\build\
        
test_script:
    - cmd: >-
        cd main 
        
        run.cmd start_zk 
        
        run.cmd test Debug .\build
        
        cd ..
        

